### ISSUE TITLE
Update stack can break link to ASG

### ISSUE THREAD

**Issue by gunnarlium** [aptoma/amp-cli#32]
If update stack triggers the creation of a new ASG, the new ASG will not be registered with the load balancer.

**Comment by aptomaKetil** [comment]
It disconnected from the CodeDeploy deployment group, at least. Did it disconnect from the ELB as well?

**Comment by gunnarlium** [comment]
Hmm, not sure ... when reverting to the old stack config, I had to reattach the stack to the elb. Needs more investigation.

**Comment by martinj** [comment]
Update stack will always require knowledge from the user on what has changed because different changes will create new resources and it could be used else where. 
`amp stack` isn't aware of resources connected to each other and it shouldn't be either, such feature should be in the `amp app` command instead.
